state_dim: 4
action_dim: 2

cbf:
  network:
    hidden_dims: [256, 256, 128]
    activation: "relu"
    dropout: 0.1
    layer_norm: true
  alpha: 0.1
  num_models: 3
  loss_weights:
    safe: 1.0
    unsafe: 1.0
    constraint: 1.0

clf:
  network:
    hidden_dims: [256, 256, 128]
    activation: "relu"
    dropout: 0.1
    layer_norm: true
  beta: 0.1
  delta: 0.01
  num_models: 3
  loss_weights:
    goal: 1.0
    constraint: 1.0
    positive: 0.1

dynamics:
  network:
    hidden_dims: [512, 512, 256]
    activation: "relu"
    dropout: 0.1
    layer_norm: true
  num_models: 5
  residual: true
  output_activation: null

training:
  batch_size: 256
  learning_rate: 0.001
  max_epochs: 1000
  cbf_update_freq: 10
  clf_update_freq: 10
  model_update_freq: 5
  buffer_capacity: 100000
  log_freq: 100
  save_freq: 1000

controller:
  safety_margin: 0.1
  feasibility_margin: 0.1
  use_qp_solver: false

device: "cpu"
experiment_name: "safe_planning"
seed: 42